version: '3.5'

services:
  api1: &api
    #image: jeanlucafp/rinhabackend2024java:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    depends_on:
      - postgres
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app
      - SPRING_DATASOURCE_USERNAME=jeanfernandes
      - SPRING_DATASOURCE_PASSWORD=1234
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  api2:
    <<: *api
    hostname: api2

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  postgres:
    image: postgres:latest
    command: 'postgres -c config_file=/etc/postgresql/pg.config'
    hostname: postgres
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=jeanfernandes
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
    volumes:
      - ./dbconfig/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./dbconfig/pg.config:/etc/postgresql/pg.config
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

networks:
  rinha:
    driver: bridge