version: '3.5'

services:
  db:
    image: postgres:latest
    command: 'postgres -c shared_buffers=640MB -c max_connections=330 -c effective_cache_size=1GB -c maintenance_work_mem=384MB'
    hostname: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    networks:
      - rinha
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.2GB'

networks:
  rinha:
    driver: bridge