version: "3.5"

services:
  api01: &api
    image: jeanlucafp/rinhabackendgo:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    hostname: api01
    environment:
      - DATABASE_URL=postgres://jeanfernandes:1234@db:5432/app
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=jeanfernandes
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
      - "2345:5432"
    volumes:
      - ./dbconfig/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dbconfig/config.conf:/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "db", "-p", "5432", "-q"]
      interval: 10s
      timeout: 5s
      retries: 5 
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.8"
          memory: "300MB"

networks:
  default:
    driver: bridge
    name: rinha-go